QuarkAnswerBundle:
    resource: "@QuarkAnswerBundle/Controller/"
    type:     annotation
    prefix:   /

QuarkQuestionBundle:
    resource: "@QuarkQuestionBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
